name: infinito
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  provider: ^4.1.3
  carousel_pro: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0
  transparent_image: ^1.0.0
  alphabet_list_scroll_view: ^1.0.6
  image_picker: ^0.6.7+1
  image_cropper: ^1.2.2
  uuid: ^2.0.4
  dio: ^3.0.9
  brasil_fields: ^0.2.0
  geolocator: ^5.3.2+2
  sliding_up_panel: ^1.0.2
  screenshot: ^0.1.1
  gallery_saver: ^2.0.1
  flutter_signin_button: ^1.0.0
  url_launcher: ^5.4.11
  map_launcher: ^0.5.0
  mask_text_input_formatter: ^1.0.7
  keyboard_actions: ^3.2.1+1
  cloud_functions: ^0.5.0
  firebase_messaging: ^6.0.16
  flushbar: ^1.10.4
  google_sign_in: 4.5.5


  cached_network_image:








dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.2.0

flutter_icons:
  # image_path_android: "assets/images/logo_infinito_orange.png"
  # image_path_ios: "assets/images/logo_infinito_orange.png"
  # android: true # can specify file name here e.g. "ic_launcher"
  # ios: true # can specify file name here e.g. "My-Launcher-Icon"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/background.png
    - assets/images/
    - assets/logo_infinito_animado.flr

 
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700



