name: infinito
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  firebase_crashlytics: ^0.1.3+3
  flutter_bloc: 
  sliding_sheet: 
  hive:
  photo_view: 


  flutter_modular: 
  shared_preferences: 
  path_provider: 
  firebase_auth: 
  google_sign_in: 
  cloud_firestore: 
  cached_network_image:
  url_launcher: 
  flutter_email_sender: 
  flare_flutter:
  font_awesome_flutter: 
  flutter_launcher_icons: 
  flutter_cache_manager: 
  flutter_staggered_animations: 
  intl:
  solid_bottom_sheet: ^0.1.9
  get: ^3.11.1
  flutter_swiper: ^1.1.6


  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/logo_infinito_orange.png"
  image_path_ios: "assets/images/logo_infinito_orange.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/background.png
    - assets/images/
    - assets/logo_infinito_animado.flr

 
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700



scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
